#!/bin/zsh

# DIRECTORIES
export DATA=/data
export CONFIG=$DATA/configuration
export XDG_CONFIG_HOME=~/.config

# APPLICATIONS
export EDITOR=nvim

# GO
export GOPATH=$XDG_CONFIG_HOME/go
export PATH="/usr/lib/go-1.10/bin:$GOPATH/bin:$PATH"
