#!/bin/zsh

# DIRECTORIES
export DATA=/data
export CONFIG=$DATA/configuration
export XDG_CONFIG_HOME=~/.config

# APPLICATIONS
export EDITOR=nvim

# GO
export GOPATH=$XDG_CONFIG_HOME/go
export PATH="$DATA/programs/standalone/zig:$PATH"
