alias o="xdg-open"
alias p="ptpython3"
alias P="$EDITOR -R -"
alias lP="l|P"
alias llP="ll|P"
alias l="ls --color=always --classify --group-directories-first"
alias cl="clear && l"
alias la="l --almost-all"
alias ll="la -l --si"
