alias r="source ~/.zshenv;source ~/.zshrc"
alias p="sudo pacman"
alias o="xdg-open"
alias apt="sudo apt"
alias awk="gawk" # Always use gawk
alias s="sudo systemctl"
alias vim="nvim"
alias ipy="ipython3"
alias P="$EDITOR -R -"
alias lP="l|P"
alias llP="ll|P"
alias l="ls --color=always --classify --group-directories-first"
alias cl="clear && l"
alias la="l --almost-all"
alias ll="la -l --si"
