music_directory "$XDG_MUSIC_DIR/library"
playlist_directory "$XDG_MUSIC_DIR/0_playlists"
db_file "$XDG_CONFIG_HOME/mpd/database"
pid_file "$XDG_CONFIG_HOME/mpd/pid"
state_file "$XDG_CONFIG_HOME/mpd/state"
sticker_file "$XDG_CONFIG_HOME/mpd/sticker.sql"
