name: CI
on:
  pull_request:
  push:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: flox/install-flox-action@v2
      - run: sudo apt install zsh gnupg
      - name: Install
        run: |
          # /data conflicts with GitHub Actions
          mkdir "$HOME/data"
          export install_data="$HOME/data"
          # work conflicts with GitHub Actions
          export install_user_dirs=false
          export change_repo_to_ssh=false
          ./install_data.sh
      - name: Show Home Directory
        run: tree -L 2 "$HOME"
      - name: Test
        run: |
          zsh -c 'e --version'
          zsh -c 'rg --version'
