name: CI
on:
  pull_request:
  push:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: flox/install-flox-action@v2
      - run: sudo apt install zsh gnupg
      - name: Install
        run: |
          # /data conflicts with GitHub Actions
          export install_data="$HOME/data"
          mkdir "$install_data"
          export install_home="$HOME/home"
          mkdir "$install_home"
          export install_xdg_config_home="$install_home/.config"
          mkdir "$install_xdg_config_home"
          ./install_data.sh
      - name: Show Directories
        run: |
          tree -a -L 2 "$HOME/data"
          tree -a -L 2 "$HOME/home"
      - name: Test Neovim
        shell: 'HOME="$HOME/home" XDG_CONFIG_HOME="$HOME/.config" script -q -e -c "zsh -i -e {0}"'
        run: e --version
      - name: Test RipGrep
        shell: 'HOME="$HOME/home" XDG_CONFIG_HOME="$HOME/.config" script -q -e -c "zsh -i -e {0}"'
        run: rg --version
      # - name: Benchmark Zsh
      #   run: |
      #     export HOME="$HOME/home"
      #     export XDG_CONFIG_HOME="$HOME/.config"
      #     $HOME/cfg/sh/zsh-bench/zsh-bench
