name: CI
on:
  pull_request:
  push:

env:
  test_home: "${{github.workspace}}/test_home"
  test_data: "${{github.workspace}}/test_data"
  test_xdg_config_home: "${{github.workspace}}/test_xdg_config_home"

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: flox/install-flox-action@v2
      - run: sudo apt install zsh gnupg
      - name: Install
        run: |
          # /data conflicts with GitHub Actions
          export install_data="${test_data}"
          mkdir "$install_data"
          export install_home="${test_home}"
          mkdir "$install_home"
          export install_xdg_config_home="${test_xdg_config_home}"
          mkdir "$install_xdg_config_home"
          ./install_data.sh
      - name: Show Directories
        run: |
          tree -a -L 2 "${test_data}"
          tree -a -L 2 "${test_home}"
          tree -a -L 2 "${test_xdg_config_home}"
      - name: Create isolated-zsh
        run: |
          zsh=/home/runner/isolated-zsh
          tee $zsh << EOF
          #!/bin/bash
          exec env --ignore-environment - \\
            HOME=$test_home \\
            XDG_CONFIG_HOME=$test_xdg_config_home \\
            TERM=xterm \\
            IGTD_SH_LOADER_VERBOSE=true \\
            script --quiet --return --command "zsh -i -e -s"
          EOF
          chmod +x $zsh
      - name: Test Neovim
        shell: "bash -c \"cat {0} | /home/runner/isolated-zsh\""
        run: e --version
      - name: Test RipGrep
        shell: "bash -c \"cat {0} | /home/runner/isolated-zsh\""
        run: rg --version
      # - name: Benchmark Zsh
      #   run: |
      #     export HOME="$HOME/home"
      #     export XDG_CONFIG_HOME="$HOME/.config"
      #     $HOME/cfg/sh/zsh-bench/zsh-bench
