name: CI
on:
  pull_request:
  push:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: flox/install-flox-action@v2
      - run: sudo apt install zsh gnupg
      - name: Install
        run: |
          # /data conflicts with GitHub Actions
          mkdir "$HOME/data"
          export install_data="$HOME/data"
          mkdir "$HOME/home"
          export install_home="$HOME/home"
          mkdir "$HOME/home/.config"
          export install_xdg_config_home="$HOME/home/.config"
          ./install_data.sh
      - name: Show Directories
        run: |
          tree -a -L 2 "$HOME/data"
          tree -a -L 2 "$HOME/home"
      - name: Test
        run: |
          export HOME="$HOME/home"
          export XDG_CONFIG_HOME="$HOME/home/.config"
          zsh -i -c 'source $HOME/.zshrc ; e --version'
          zsh -i -c 'source $HOME/.zshrc ; rg --version'
